version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: payments_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/payments_db?schema=public
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      RABBITMQ_EXCHANGE: payments.exchange
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    environment:
      PORT: 3001
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      RABBITMQ_EXCHANGE: payments.exchange
    ports:
      - '3001:3001'
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data:
