services:
  postgres:
    image: postgres:15-alpine
    container_name: desafio-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    container_name: desafio-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 10

  payment-service:
    build:
      context: ./payment-service
    container_name: desafio-payment-service
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ecommerce
      RABBITMQ_URL: amqp://rabbitmq:5672
      EXCHANGE_NAME: ecommerce.events
      NOTIFICATION_ROUTING_KEY: notification.transaction
    ports:
      - "3000:3000"

  notification-service:
    build:
      context: ./notification-service
    container_name: desafio-notification-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      PORT: 3001
      RABBITMQ_URL: amqp://rabbitmq:5672
      EXCHANGE_NAME: ecommerce.events
      QUEUE_NAME: notifications.queue
      ROUTING_KEY: notification.transaction
    ports:
      - "3001:3001"
